# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

# Ebuild generated by g-pypi <http://pypi.python.org/pypi/g-pypi/>

EAPI="4"

inherit distutils

MY_PN="Unipath"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Object-oriented alternative to os/os.path/shutil"
HOMEPAGE="http://sluggo.scrapping.cc/python/unipath/"
SRC_URI="http://sluggo.scrapping.cc/python/unipath/${MY_P}.tar.gz"
LICENSE="PSF-2.4"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
S="${WORKDIR}/${MY_P}"
