#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

start() {
	ebegin "Starting mjpg-streamer"
	/sbin/start-stop-daemon --start --quiet --exec ${MJPGSTREAMER_EXEC} \
	-- -b -i "${INPUT_PLUGIN} ${INPUT_PLUGIN_OPTS}" -o "${OUTPUT_PLUGIN} ${OUTPUT_PLUGIN_OPTS}"
	eend $?
}

stop() {
	ebegin "Stopping mjpg-streamer"
	start-stop-daemon --stop --quiet --exec ${MJPGSTREAMER_EXEC}
	eend $?
}
